services:
  db:
    image: mysql:8.0
    container_name: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog_db
    volumes:
      # [내 맥북의 폴더 경로] : [컨테이너 내부의 데이터 저장 경로]
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    # [추가] DB가 진짜 살아있는지 확인하는 로직
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: blog-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blog_db?serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build: ./frontend
    container_name: blog-frontend-vue
    ports:
      - "5173:5173"
    # 소스 코드 수정을 실시간으로 반영하기 위한 볼륨 설정 (개발 편의성)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started