spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins:
      - https://blog-front-temp.vercel.app
      - https://hc-domain.site
      - http://localhost:5173

jwt:
  secret: ${JWT_SECRET_KEY}

file:
  dir: /app/img_data/
